### PR TITLE
Changed cards layout of my rentals page

### PR DESCRIPTION
**Pull request by nafriedman**
Ready for review. 

When opening app on a large screen, each row will have two rental cards. 

Screen Shot 2021-08-19 at 3 04 44 PM

### CODE REVIEW

**Comment by Tien9320** [comment]
Can you add some padding for the Cards, too?

**Comment by nafriedman** [comment]
> Can you add some padding for the Cards, too?

Good idea. I'm on it.

**Comment by nafriedman** [comment]
@Tien9320 is this better? 

Screen Shot 2021-08-19 at 4 16 37 PM

**Comment by MmeIsabelle** [comment]
Nice improvement

**Pull request merged**
