### PR TITLE
Added homepage and footer

### PR DESCRIPTION
**Pull request by Tien9320**
Screen Shot 2021-08-17 at 11 53 58 AM

- I added a banner with search bar and a footer. 

- I'm gonna work with nav-bar in a different branch. 

- I will add some card into the middle of homepage after we finish with model

### CODE REVIEW

**Comment by nafriedman** [comment]
This looks awesome 🚀 🚀

**Comment by nafriedman** [comment]
@MmeIsabelle @dylancherry98 do you guys have any ideas to add for this??

**Comment by dylancherry98** [comment]
Looks great! 

May I please suggest the following vocabulary/grammar changes:

The header should read:
Soundlet makes it easy to rent audio equipment!

The paragraph should read:
Whether you're looking for equipment to rent or want to make money by renting out your equipment.
Let Soundlet help you!


Awesome work!

**Comment by dylancherry98** [comment]
Thoughts? @nafriedman @MmeIsabelle @Tien9320

**Comment by MmeIsabelle** [comment]
@Tien9320 @dylancherry98 @nafriedman I would say "Whether you are" without the contraction.
The rest sounds good and look good too!

**Pull request merged**
