### PR TITLE
Created seed file.

### PR DESCRIPTION
**Pull request by dylancherry98**
Hi Team,

I created a _seed.rb_ file that creates 5 'User' instances and 10 'Listing' instances.

I tested it in the console and it seems to be working.

I also implemented some console messages to help us visualize what's happening when seeding:

image

Please let me know what you all think.

### CODE REVIEW

**Comment by dylancherry98** [comment]
What do you think? @nafriedman

**Comment by nafriedman** [comment]
Prices should be floats not strings

**Comment by dylancherry98** [comment]
Thank you for catching that, @nafriedman . I'll fix it right away.

**Comment by dylancherry98** [comment]
Fixed! @nafriedman

**Pull request merged**
